export const projectsData = [
  {
    id: 1,
    title: 'Smart Crop Monitoring System',
    category: 'agriculture',
    location: 'Punjab, India',
    date: 'Jan 2024',
    team: 12,
    description: 'Deployed precision mapping drones across 5000+ acres for real-time crop health monitoring and yield prediction.',
    image: '/agriculture-icon.png',
    status: 'Completed',
    impact: '35% increase in yield',
    budget: 250,
    duration: 6,
    roi: 320,
    technologies: ['AI', 'Drones', 'IoT', 'ML'],
    teamMembers: ['Raj Kumar', 'Priya Singh', 'Amit Patel'],
    testimonial: 'Exceptional results and professional execution.',
    testimonialAuthor: 'Farmer Association Lead',
    rating: 4.8,
  },
  {
    id: 2,
    title: 'Bridge Inspection Automation',
    category: 'infrastructure',
    location: 'Mumbai, India',
    date: 'Dec 2023',
    team: 8,
    description: 'Automated inspection of 50+ bridges using AI-powered robots, reducing inspection time by 70%.',
    image: '/infrastructure-icon.png',
    status: 'Completed',
    impact: '70% time reduction',
    budget: 180,
    duration: 4,
    roi: 280,
    technologies: ['Robotics', 'AI', 'Computer Vision'],
    teamMembers: ['Vikram Singh', 'Neha Sharma', 'Rohan Gupta'],
    testimonial: 'Transformed our inspection process completely.',
    testimonialAuthor: 'Infrastructure Ministry',
    rating: 4.9,
  },
  {
    id: 3,
    title: 'Border Patrol Enhancement',
    category: 'defense',
    location: 'Rajasthan, India',
    date: 'Nov 2023',
    team: 15,
    description: 'Deployed autonomous surveillance drones for enhanced border security with real-time threat detection.',
    image: '/defence-icon.png',
    status: 'Ongoing',
    impact: '99.2% detection rate',
    budget: 500,
    duration: 12,
    roi: 450,
    technologies: ['Drones', 'AI', 'Surveillance', 'Real-time Analytics'],
    teamMembers: ['Col. Rajesh', 'Dr. Ananya', 'Capt. Arjun'],
    testimonial: 'Critical for national security operations.',
    testimonialAuthor: 'Defense Ministry',
    rating: 4.9,
  },
  {
    id: 4,
    title: 'Disaster Response Initiative',
    category: 'disaster',
    location: 'Kerala, India',
    date: 'Oct 2023',
    team: 20,
    description: 'Rapid deployment of rescue robots and drones for flood relief operations, saving 500+ lives.',
    image: '/disaster-icon.png',
    status: 'Completed',
    impact: '500+ lives saved',
    budget: 300,
    duration: 3,
    roi: 999,
    technologies: ['Rescue Robots', 'Drones', 'Real-time Coordination'],
    teamMembers: ['Dr. Suresh', 'Meera Nair', 'Arun Pillai'],
    testimonial: 'Saved countless lives during the crisis.',
    testimonialAuthor: 'State Disaster Management',
    rating: 5.0,
  },
  {
    id: 5,
    title: 'Environmental Monitoring Network',
    category: 'environment',
    location: 'Himalayas, India',
    date: 'Sep 2023',
    team: 10,
    description: 'Installed IoT sensors and drones for real-time environmental monitoring and climate data collection.',
    image: '/environment-icon.png',
    status: 'Ongoing',
    impact: '10,000+ data points/day',
    budget: 150,
    duration: 8,
    roi: 200,
    technologies: ['IoT', 'Drones', 'Data Analytics', 'Cloud'],
    teamMembers: ['Dr. Vikram', 'Priya Sharma', 'Nikhil Desai'],
    testimonial: 'Invaluable data for climate research.',
    testimonialAuthor: 'Environmental Ministry',
    rating: 4.7,
  },
  {
    id: 6,
    title: 'Smart City Infrastructure',
    category: 'infrastructure',
    location: 'Bangalore, India',
    date: 'Aug 2023',
    team: 18,
    description: 'Integrated robotics and automation for smart city infrastructure management and maintenance.',
    image: '/infrastructure-icon.png',
    status: 'Ongoing',
    impact: '40% efficiency gain',
    budget: 400,
    duration: 10,
    roi: 350,
    technologies: ['Robotics', 'IoT', 'AI', 'Automation'],
    teamMembers: ['Rajesh Kumar', 'Anjali Verma', 'Sanjay Rao'],
    testimonial: 'Best smart city implementation in India.',
    testimonialAuthor: 'City Administration',
    rating: 4.8,
  },
  {
    id: 7,
    title: 'Agricultural Automation Hub',
    category: 'agriculture',
    location: 'Haryana, India',
    date: 'Jul 2023',
    team: 14,
    description: 'Established automation center for precision farming with collaborative robots and AI systems.',
    image: '/agriculture-icon.png',
    status: 'Completed',
    impact: '50% cost reduction',
    budget: 220,
    duration: 5,
    roi: 310,
    technologies: ['Collaborative Robots', 'AI', 'Precision Farming'],
    teamMembers: ['Harpreet Singh', 'Kavya Nair', 'Deepak Sharma'],
    testimonial: 'Revolutionized farming practices in the region.',
    testimonialAuthor: 'Agricultural Department',
    rating: 4.7,
  },
  {
    id: 8,
    title: 'Coastal Defense System',
    category: 'defense',
    location: 'Goa, India',
    date: 'Jun 2023',
    team: 16,
    description: 'Advanced surveillance and defense system for coastal security with autonomous patrol units.',
    image: '/defence-icon.png',
    status: 'Completed',
    impact: '100% coverage',
    budget: 350,
    duration: 7,
    roi: 400,
    technologies: ['Autonomous Drones', 'Surveillance', 'AI Detection'],
    teamMembers: ['Adm. Vikram', 'Lt. Sharma', 'Cdr. Patel'],
    testimonial: 'Enhanced coastal security significantly.',
    testimonialAuthor: 'Navy Command',
    rating: 4.9,
  },
];
